### ISSUE TITLE
hosted version down

### ISSUE THREAD

**Issue by splace** [Peer5/ShareFest#77]
in fact the whole site:  http://sharefest.me  has ben down for a month or more

**Comment by shacharz** [comment]
It's upw now, thanks for the notice.

**Comment by splace** [comment]
unfortunately its still down for me.

and http://www.downforeveryoneorjustme.com says its down for everyone.

**Comment by D-side** [comment]
Still down. Cloudflare claims it's unable to establish an SSL connection to an origin server.

**Comment by shaharmor** [comment]
Fixed
