### ISSUE TITLE
Browser Issue

### ISSUE THREAD

**Issue by iHamex** [Peer5/ShareFest#87]
Hello guys,
i just installed Sharefest in two location (my local mamp and dedicated server), but the problem is every time i browse, the "Sorry! Your browser is not supported. Please use latest Chrome (26+) or Firefox (22+) to try out Sharefest." will appear (chrome 54). changing regex or manipulating in scripts does not work.

is there any thing that i should to know before starting the server?
btw, official site demo works perfect (may or maybe not bacause of peer5 api usage).
Thanks

**Comment by derhuerst** [comment]
Chromium 56 doesn't give me an error.

**Comment by varma-ksbh** [comment]
Hi iHamex, have u found solution to the issue? Even I am unable to run it on Chrome 54 but offical site demo works

**Comment by iHamex** [comment]
It doesn't give me an error anymore. 
i made some changes on it, if you want to try that just give me your email to send you mine.
just upload it to your web server and check whats wrong with yours. 
hope it'll help you.

**Comment by varma-ksbh** [comment]
That's would be great..
Pls send it to varma.ksbh7@gmail.com
Thanks in advance
